name: dokVision
title: dokVision | World through my lens
description: Portfolio website of Anusha Datta.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
show_get_theme_btn: false
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Portfolio
    url: /tags
  # - title: Feed
  #   url: /feed.xml
email: youremail@test.com
email_id: anusha.datta@gmail.com
# See: https://disqus.com/
# disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
# formspree_form_id: formspree_form_id
